language: cpp
matrix:
 include:
  - compiler: gcc
    os: linux
  - compiler: clang
    os: osx

addons:
 apt:
  sources:
   - ubuntu-toolchain-r-test
  packages:
   - gcc-4.8
   - g++-4.8
   
script:
 - chmod u+x aemake
 - ./aemake gmake 
 - make config=release

notifications:
 email: false

before_deploy:
 - git fetch --tags

deploy:
 provider: releases
 overwrite: true
 skip_cleanup: true
 draft: false
 api_key:
  secure: uDRbRdC2a8h2sbXu9oYZEN4r/3GhK9NACzQVJGK7JSX+F50VJ9oQ4KPSphGUBTyhCWRs7SmkDsiOS2hy6n+PWjO+xtBxB4OfrRz7h+Hg8HIobj4cue9zHia0w2X+egzfuiuQ2ZRxFM2XgBRG9wxN76Stw7SRXtpNqD4lnRG+8DkIyYtcrnnqo1zk8xSWM2OBvdu+8mDtckhgSkc38C0/bFXeeL5ZKOOXWGFl8vphY5nV0fmUwacnkQRa4hSwo5uULZIZcSh7p9gDcw62bBWmhAda1zDEjojwdcWYn3jUEEtdy26zaJaCbzMKrx2g0npqraU3pdAaj738lg/M9Yqngvt3dT1953OSTbI3hcxZ0NQfXskFWDqWN9bMii8RFyL9UH68k6SD+qH3x9MLF2GQvGs0p3GVgJSKlgUjRrZR7j7ixiLvwjrGDuS2Td5LIBsA0oY2/wiW65kjv1gtkkKQVDSpsVUhVMNwMN6J80pgJv5ZzZYcClk7xe7mPEzz14ofdSlKHRGgpAGT5l3V2UE5TEkZrziYLEX5YXODz9TV1YvF2p9lEdfZ66omvDmOImiZ35F7p522XwfDnHMY759h0vn7LV6VJ/zeYm9tovjzxlvM6/EJncjGobWhABYtxQBCNd6hVQTApAdZmG10gIE6hIgNDksWEUOA7Zw3AQWPqNg=
 file_glob: true
 file:
  - amalgamate-*.zip
 on:
  tags: true
