language: cpp
matrix:
 include:
  - compiler: gcc
    os: linux
  - compiler: clang
    os: osx

addons:
 apt:
  sources:
   - ubuntu-toolchain-r-test
  packages:
   - gcc-4.8
   - g++-4.8
   
script:
 - chmod u+x aemake
 - ./aemake gmake 
 - make config=release

notifications:
 email: false

before_deploy:
 - git fetch --tags

deploy:
 provider: releases
 overwrite: true
 skip_cleanup: true
 draft: false
 api_key:
  secure: LS9Qd0Fof524weijeFwTUVzEsPLlOKrp9mgriiNi0JpBQGGzbFAErZ9T7AaxdOB3CRD/lUrGs/ObOJVplrMpqxlF12Z6co2nGoDRYUoz3Y6Q5NcbYyGPjB8pAk+Eoi3rk13tO4kLdrvvqplvkPsqo75zGTchvl6yHk439zehoTZgPiG40tp/j+5RGNhHxwpgNsGfUn7gqaz81+Nt8by075QFIRHdhkUfJC7YZS0lnFm+ik/I8dB2aTGN53R2i5fug4OhTWzzBo8Limk8InZAjyKvm/CM3IOOfkhDiZdfVcz6rz3/O1zOzFCBowGS1HKEaC4+p5eK0zylkKReQnNlcYhff9/M2gNw4Ax18uP3gkyyLy91xjT9cxz+QX4bVJddbjhH5qrByJlOqh0ba914MIUDZg1k2SuXqxi8ugtph+HfIMtGwoIGKbzyYvQD492/zNL1msfLNDp+XlWBvluVB87AHKeUXjFS+fFaFGh+rDpJcySF+t42CP04MyXkn9a41GximyQ9Ryf24Loz0OPtKPaza+4L8nAdk0HZtatn8BFpNI9zr6y0Gr2ky82KTHSx9OH0B3fgKA8vtau+kHre/x35zbQ26MHZRu7OwuxsShn81Y3QCm3swi7p73bc4ysPjerdKPLhS60Gz0xpKWtx1gpR2TmMxLjymUBAIkYQgQc=
 file_glob: true
 file:
  - amalgamate-*.zip
 on:
  tags: true
